-- Supabase SQL Editor 실행 순서: 2/5
-- 158개 표준 건강검진 검사 항목
BEGIN;

INSERT INTO labs_item_master (
    item_code, item_name_ko, item_type, item_category, specimen_type,
    result_type, standard_unit, item_description, is_active
)
VALUES
    ('MEDICAL_INTERVIEW_CONSULTATION', '문진·진찰 및 상담', 'QUESTIONNAIRE', 'QUESTIONNAIRE', NULL, 'TEXT', NULL, '설문 또는 문진으로 얻는 검사 결과.', TRUE),
    ('HEIGHT', '신장', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'cm', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('WEIGHT', '체중', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'kg', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('WAIST_CIRCUMFERENCE', '허리둘레', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'cm', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('BMI', '체질량지수', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'kg/m2', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('BODY_FAT_PERCENTAGE', '체지방률', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', '%', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('MUSCLE_MASS', '근육량', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'kg', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('BODY_FAT_MASS', '체지방량', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'kg', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('STRESS_ASSESSMENT', '스트레스 평가', 'QUESTIONNAIRE', 'QUESTIONNAIRE', NULL, 'MIXED', NULL, '설문 또는 문진으로 얻는 검사 결과.', TRUE),
    ('METABOLIC_AGE', '대사생체나이', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'year', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('SYSTOLIC_BP', '수축기혈압', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'mmHg', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('DIASTOLIC_BP', '이완기혈압', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', 'mmHg', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('VISUAL_ACUITY_LEFT', '시력(좌)', 'OBSERVATION', 'VITAL', NULL, 'MIXED', NULL, '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('VISUAL_ACUITY_RIGHT', '시력(우)', 'OBSERVATION', 'VITAL', NULL, 'MIXED', NULL, '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('HEARING_1000HZ_LEFT', '청력 1000Hz(좌)', 'OBSERVATION', 'FUNCTION', NULL, 'MIXED', 'dB', '신체 기능을 평가하는 검사 항목.', TRUE),
    ('HEARING_1000HZ_RIGHT', '청력 1000Hz(우)', 'OBSERVATION', 'FUNCTION', NULL, 'MIXED', 'dB', '신체 기능을 평가하는 검사 항목.', TRUE),
    ('ECG', '심전도', 'REPORT', 'FUNCTION', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('CHEST_XRAY_PA', '흉부방사선 직접촬영(PA)', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('ORAL_EXAM', '구강검진', 'REPORT', 'OTHER', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('URINE_LEUKOCYTE', '요백혈구', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_NITRITE', '요아질산염', 'OBSERVATION', 'LAB', 'URINE', 'CODE', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_PH', '요산도', 'OBSERVATION', 'LAB', 'URINE', 'NUMBER', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_PROTEIN', '요단백', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 단백 검출 여부 또는 정도.', TRUE),
    ('URINE_GLUCOSE', '요당', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_KETONE', '요케톤체', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_UROBILINOGEN', '요유로빌리노겐', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_BILIRUBIN', '요빌리루빈', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_OCCULT_BLOOD', '요잠혈', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SPECIFIC_GRAVITY', '요비중', 'OBSERVATION', 'LAB', 'URINE', 'NUMBER', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SEDIMENT_RBC', '요침사 적혈구', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', '/HPF', '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SEDIMENT_WBC', '요침사 백혈구', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', '/HPF', '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SEDIMENT_CAST', '요침사 원주', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', '/LPF', '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SEDIMENT_OTHER', '요침사 기타', 'OBSERVATION', 'LAB', 'URINE', 'TEXT', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SEDIMENT_BACTERIA', '요침사 세균', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', NULL, '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_SEDIMENT_EPITHELIAL_CELL', '요침사 상피세포', 'OBSERVATION', 'LAB', 'URINE', 'MIXED', '/HPF', '소변 검체로 측정하는 검사 항목.', TRUE),
    ('URINE_MICROALBUMIN_CREATININE_RATIO', '요미세알부민/크레아티닌 비율', 'OBSERVATION', 'LAB', 'URINE', 'NUMBER', 'mg/g', '소변 검체로 측정하는 검사 항목.', TRUE),
    ('FECAL_OCCULT_BLOOD_QUANT', '분변잠혈 정량', 'OBSERVATION', 'LAB', 'STOOL', 'MIXED', NULL, '대변 검체로 측정하는 검사 항목.', TRUE),
    ('STOOL_PARASITE_SMEAR', '분변 기생충 도말검사', 'OBSERVATION', 'LAB', 'STOOL', 'CODE', NULL, '대변 검체로 측정하는 검사 항목.', TRUE),
    ('HEMATOCRIT', '헤마토크리트', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HEMOGLOBIN', '혈색소', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'g/dL', '혈액 속 헤모글로빈 농도.', TRUE),
    ('WBC_COUNT', '백혈구수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '10^3/uL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('RBC_COUNT', '적혈구수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '10^6/uL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('PLATELET_COUNT', '혈소판수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '10^3/uL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('MCV', '평균적혈구용적', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'fL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('MCH', '평균적혈구혈색소', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'pg', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('MCHC', '평균적혈구혈색소농도', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'g/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('RDW', '적혈구분포계수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('PDW', '혈소판분포계수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'fL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('MPV', '평균혈소판용적', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'fL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('PCT', '혈소판백분율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('NEUTROPHIL_PERCENT', '호중구백분율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('EOSINOPHIL_PERCENT', '호산구백분율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('BASOPHIL_PERCENT', '호염구백분율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('MONOCYTE_PERCENT', '단핵구백분율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('LYMPHOCYTE_PERCENT', '림프구백분율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('ESR', '적혈구침강속도', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mm/hr', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('AST', '에이에스티(AST)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '간·근육 등에 존재하는 효소 수치.', TRUE),
    ('ALT', '에이엘티(ALT)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '주로 간세포와 관련된 효소 수치.', TRUE),
    ('GAMMA_GTP', '감마지티피(γ-GTP)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '담도·간 기능 관련 효소 수치.', TRUE),
    ('ALP', '알칼리인산분해효소(ALP)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TOTAL_BILIRUBIN', '총빌리루빈', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('DIRECT_BILIRUBIN', '직접빌리루빈', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('INDIRECT_BILIRUBIN', '간접빌리루빈(계산값)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TOTAL_PROTEIN', '총단백', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'g/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('ALBUMIN', '알부민', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'g/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('AG_RATIO', '알부민/글로불린 비율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('FIB4', 'FIB-4 간섬유화 지수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('FASTING_GLUCOSE', '공복혈당', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '공복 상태에서 측정한 혈당.', TRUE),
    ('HBA1C', '당화혈색소(HbA1c)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TOTAL_CHOLESTEROL', '총콜레스테롤', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TRIGLYCERIDES', '중성지방', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HDL_CHOLESTEROL', '고밀도(HDL) 콜레스테롤', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('LDL_CHOLESTEROL', '저밀도(LDL) 콜레스테롤', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('BUN', '요소질소(BUN)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('SERUM_CREATININE', '혈청크레아티닌', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈청 크레아티닌 농도.', TRUE),
    ('BUN_CREATININE_RATIO', '요소질소/크레아티닌 비율', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('EGFR', '신사구체여과율(e-GFR)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mL/min/1.73m2', '크레아티닌 등을 이용해 계산한 신장 여과 기능 추정치.', TRUE),
    ('URIC_ACID', '요산', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HS_CRP', '고감도 C반응단백(hs-CRP)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HEPATITIS_B_SURFACE_ANTIGEN', 'B형간염 표면항원(HBsAg)', 'OBSERVATION', 'LAB', 'BLOOD', 'MIXED', NULL, 'B형간염 바이러스 표면항원 검사.', TRUE),
    ('HEPATITIS_B_SURFACE_ANTIBODY', 'B형간염 표면항체(HBsAb)', 'OBSERVATION', 'LAB', 'BLOOD', 'MIXED', NULL, 'B형간염 표면항체 검사.', TRUE),
    ('HEPATITIS_C_ANTIBODY', 'C형간염 항체(HCV Ab)', 'OBSERVATION', 'LAB', 'BLOOD', 'MIXED', NULL, 'C형간염 항체 선별검사.', TRUE),
    ('PSA', '전립선특이항원(PSA)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('AFP', '알파태아단백(AFP)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CA19_9', 'CA 19-9', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TSH', '갑상선자극호르몬(TSH)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'uIU/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('FREE_T4', '유리티록신(Free T4)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('T3', '트리요오드티로닌(T3)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('BONE_DENSITY', '골밀도검사', 'PANEL', 'FUNCTION', NULL, 'MIXED', NULL, '여러 개별 검사 결과를 함께 구성하는 검사 묶음.', TRUE),
    ('PULMONARY_FUNCTION', '폐기능검사', 'PANEL', 'FUNCTION', NULL, 'MIXED', NULL, '여러 개별 검사 결과를 함께 구성하는 검사 묶음.', TRUE),
    ('PHQ9', '정신건강검사(우울증, PHQ-9)', 'QUESTIONNAIRE', 'QUESTIONNAIRE', NULL, 'NUMBER', 'score', '설문 또는 문진으로 얻는 검사 결과.', TRUE),
    ('CAPE15', '정신건강검사(조기정신증, CAPE-15)', 'QUESTIONNAIRE', 'QUESTIONNAIRE', NULL, 'NUMBER', 'score', '설문 또는 문진으로 얻는 검사 결과.', TRUE),
    ('KDSQC', '인지기능장애검사(KDSQ-C)', 'QUESTIONNAIRE', 'QUESTIONNAIRE', NULL, 'NUMBER', 'score', '설문 또는 문진으로 얻는 검사 결과.', TRUE),
    ('LIFESTYLE_ASSESSMENT', '생활습관평가', 'QUESTIONNAIRE', 'QUESTIONNAIRE', NULL, 'TEXT', NULL, '설문 또는 문진으로 얻는 검사 결과.', TRUE),
    ('ELDERLY_PHYSICAL_FUNCTION', '노인신체기능검사', 'OBSERVATION', 'FUNCTION', NULL, 'MIXED', NULL, '신체 기능을 평가하는 검사 항목.', TRUE),
    ('DENTAL_PLAQUE', '치면세균막검사', 'OBSERVATION', 'OTHER', NULL, 'CODE', NULL, '건강검진 결과지에서 사용하는 검사 항목.', TRUE),
    ('CERVICAL_CYTOLOGY', '자궁경부 세포검사', 'REPORT', 'OTHER', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('UPPER_GI_SERIES', '위장조영촬영', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('UPPER_GI_ENDOSCOPY', '일반 위내시경', 'REPORT', 'ENDOSCOPY', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('MAMMOGRAPHY', '유방촬영', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('THYROID_ULTRASOUND', '갑상선초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('UPPER_ABDOMINAL_ULTRASOUND', '상복부초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('GLOBULIN', '글로불린', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'g/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('LDH', '젖산탈수소효소(LDH)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('SODIUM', '나트륨', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mmol/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('POTASSIUM', '칼륨', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mmol/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CHLORIDE', '염소', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mmol/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CALCIUM', '칼슘', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('PHOSPHORUS', '인', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('MAGNESIUM', '마그네슘', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('AMYLASE', '아밀라아제', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('LIPASE', '리파아제', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('IRON', '혈청철', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ug/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TIBC', '총철결합능(TIBC)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ug/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('UIBC', '불포화철결합능(UIBC)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ug/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('FERRITIN', '페리틴', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('VITAMIN_D_25_OH', '25-OH 비타민D', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CEA', '암배아항원(CEA)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CA125', 'CA 125', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CYFRA21_1', 'CYFRA 21-1', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HE4', 'HE4', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'pmol/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('ROMA_SCORE', 'ROMA 점수', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', '%', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HIV_AG_AB', 'HIV 항원·항체', 'OBSERVATION', 'LAB', 'BLOOD', 'MIXED', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('SYPHILIS_SCREEN', '매독 선별검사', 'OBSERVATION', 'LAB', 'BLOOD', 'MIXED', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('HEPATITIS_A_ANTIBODY', 'A형간염 항체', 'OBSERVATION', 'LAB', 'BLOOD', 'MIXED', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('RHEUMATOID_FACTOR', '류마티스인자(RF)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'IU/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CK', '크레아틴키나아제(CK)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'U/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('CYSTATIN_C', '시스타틴 C', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mg/L', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('TESTOSTERONE', '테스토스테론', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'ng/dL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('FSH', '난포자극호르몬(FSH)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'mIU/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('ESTRADIOL', '에스트라디올(E2)', 'OBSERVATION', 'LAB', 'BLOOD', 'NUMBER', 'pg/mL', '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('ABO_BLOOD_GROUP', 'ABO 혈액형', 'OBSERVATION', 'LAB', 'BLOOD', 'CODE', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('RH_BLOOD_GROUP', 'Rh 혈액형', 'OBSERVATION', 'LAB', 'BLOOD', 'CODE', NULL, '혈액 검체로 측정하는 검사 항목.', TRUE),
    ('PULSE', '맥박', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', '/min', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('OXYGEN_SATURATION', '산소포화도', 'OBSERVATION', 'VITAL', NULL, 'NUMBER', '%', '신체계측 또는 활력징후 검사 항목.', TRUE),
    ('FEV1', '1초간 노력성 호기량(FEV1)', 'OBSERVATION', 'FUNCTION', NULL, 'NUMBER', 'L', '신체 기능을 평가하는 검사 항목.', TRUE),
    ('FVC', '노력성 폐활량(FVC)', 'OBSERVATION', 'FUNCTION', NULL, 'NUMBER', 'L', '신체 기능을 평가하는 검사 항목.', TRUE),
    ('FEV1_FVC_RATIO', 'FEV1/FVC 비율', 'OBSERVATION', 'FUNCTION', NULL, 'NUMBER', '%', '신체 기능을 평가하는 검사 항목.', TRUE),
    ('BONE_DENSITY_T_SCORE', '골밀도 T-score', 'OBSERVATION', 'FUNCTION', NULL, 'NUMBER', NULL, '신체 기능을 평가하는 검사 항목.', TRUE),
    ('BONE_DENSITY_Z_SCORE', '골밀도 Z-score', 'OBSERVATION', 'FUNCTION', NULL, 'NUMBER', NULL, '신체 기능을 평가하는 검사 항목.', TRUE),
    ('ABDOMINAL_CT', '복부 CT', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('LOW_DOSE_CHEST_CT', '저선량 흉부 CT', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('CORONARY_CALCIUM_CT', '관상동맥 석회화 CT', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('BRAIN_MRI', '뇌 MRI', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('BRAIN_MRA', '뇌 MRA', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('CAROTID_ULTRASOUND', '경동맥초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('ECHOCARDIOGRAPHY', '심장초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('BREAST_ULTRASOUND', '유방초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('PELVIC_ULTRASOUND', '부인과초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('PROSTATE_ULTRASOUND', '전립선초음파', 'REPORT', 'IMAGING', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('COLONOSCOPY', '대장내시경', 'REPORT', 'ENDOSCOPY', NULL, 'TEXT', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('LIVER_FIBROSIS_SCAN', '간 섬유화·지방 스캔', 'REPORT', 'IMAGING', NULL, 'MIXED', NULL, '판독 또는 소견 형태로 받는 검사 결과.', TRUE),
    ('HPV_TEST', '인유두종바이러스(HPV) 검사', 'OBSERVATION', 'LAB', 'OTHER', 'MIXED', NULL, '건강검진 결과지에서 사용하는 검사 항목.', TRUE),
    ('CBC_PANEL', '일반혈액검사 패널(CBC)', 'PANEL', 'LAB', 'BLOOD', 'TEXT', NULL, '일반혈액검사의 개별 결과를 묶는 패널.', TRUE),
    ('LIVER_FUNCTION_PANEL', '간기능검사 패널', 'PANEL', 'LAB', 'BLOOD', 'TEXT', NULL, '간 기능 관련 개별 결과를 묶는 패널.', TRUE),
    ('LIPID_PANEL', '지질검사 패널', 'PANEL', 'LAB', 'BLOOD', 'TEXT', NULL, '혈중 지질 관련 개별 결과를 묶는 패널.', TRUE),
    ('THYROID_FUNCTION_PANEL', '갑상선기능검사 패널', 'PANEL', 'LAB', 'BLOOD', 'TEXT', NULL, '갑상선 기능 관련 개별 결과를 묶는 패널.', TRUE),
    ('URINALYSIS_PANEL', '요검사 패널', 'PANEL', 'LAB', 'URINE', 'TEXT', NULL, '소변검사 개별 결과를 묶는 패널.', TRUE)
ON CONFLICT (item_code)
DO UPDATE SET
    item_name_ko = EXCLUDED.item_name_ko,
    item_type = EXCLUDED.item_type,
    item_category = EXCLUDED.item_category,
    specimen_type = EXCLUDED.specimen_type,
    result_type = EXCLUDED.result_type,
    standard_unit = EXCLUDED.standard_unit,
    item_description = EXCLUDED.item_description,
    is_active = EXCLUDED.is_active;

COMMIT;
