-- Supabase SQL Editor 실행 순서: 3/5
-- 대표 한글명·약어·동의어 250개
BEGIN;

WITH alias_data (
    item_code, alias_name, normalized_alias, alias_type, institution_name, is_active
) AS (
    VALUES
    ('MEDICAL_INTERVIEW_CONSULTATION', '문진·진찰 및 상담', '문진진찰및상담', 'STANDARD', NULL, TRUE),
    ('HEIGHT', '신장', '신장', 'STANDARD', NULL, TRUE),
    ('WEIGHT', '체중', '체중', 'STANDARD', NULL, TRUE),
    ('WAIST_CIRCUMFERENCE', '허리둘레', '허리둘레', 'STANDARD', NULL, TRUE),
    ('BMI', '체질량지수', '체질량지수', 'STANDARD', NULL, TRUE),
    ('BODY_FAT_PERCENTAGE', '체지방률', '체지방률', 'STANDARD', NULL, TRUE),
    ('MUSCLE_MASS', '근육량', '근육량', 'STANDARD', NULL, TRUE),
    ('BODY_FAT_MASS', '체지방량', '체지방량', 'STANDARD', NULL, TRUE),
    ('STRESS_ASSESSMENT', '스트레스 평가', '스트레스평가', 'STANDARD', NULL, TRUE),
    ('METABOLIC_AGE', '대사생체나이', '대사생체나이', 'STANDARD', NULL, TRUE),
    ('SYSTOLIC_BP', '수축기혈압', '수축기혈압', 'STANDARD', NULL, TRUE),
    ('DIASTOLIC_BP', '이완기혈압', '이완기혈압', 'STANDARD', NULL, TRUE),
    ('VISUAL_ACUITY_LEFT', '시력(좌)', '시력좌', 'STANDARD', NULL, TRUE),
    ('VISUAL_ACUITY_RIGHT', '시력(우)', '시력우', 'STANDARD', NULL, TRUE),
    ('HEARING_1000HZ_LEFT', '청력 1000Hz(좌)', '청력1000HZ좌', 'STANDARD', NULL, TRUE),
    ('HEARING_1000HZ_RIGHT', '청력 1000Hz(우)', '청력1000HZ우', 'STANDARD', NULL, TRUE),
    ('ECG', '심전도', '심전도', 'STANDARD', NULL, TRUE),
    ('CHEST_XRAY_PA', '흉부방사선 직접촬영(PA)', '흉부방사선직접촬영PA', 'STANDARD', NULL, TRUE),
    ('ORAL_EXAM', '구강검진', '구강검진', 'STANDARD', NULL, TRUE),
    ('URINE_LEUKOCYTE', '요백혈구', '요백혈구', 'STANDARD', NULL, TRUE),
    ('URINE_NITRITE', '요아질산염', '요아질산염', 'STANDARD', NULL, TRUE),
    ('URINE_PH', '요산도', '요산도', 'STANDARD', NULL, TRUE),
    ('URINE_PROTEIN', 'Protein (urine)', 'PROTEINURINE', 'SYNONYM', NULL, TRUE),
    ('URINE_PROTEIN', '요단백', '요단백', 'STANDARD', NULL, TRUE),
    ('URINE_GLUCOSE', '요당', '요당', 'STANDARD', NULL, TRUE),
    ('URINE_KETONE', '요케톤체', '요케톤체', 'STANDARD', NULL, TRUE),
    ('URINE_UROBILINOGEN', '요유로빌리노겐', '요유로빌리노겐', 'STANDARD', NULL, TRUE),
    ('URINE_BILIRUBIN', '요빌리루빈', '요빌리루빈', 'STANDARD', NULL, TRUE),
    ('URINE_OCCULT_BLOOD', 'Occult blood (urine)', 'OCCULTBLOODURINE', 'SYNONYM', NULL, TRUE),
    ('URINE_OCCULT_BLOOD', '요잠혈', '요잠혈', 'STANDARD', NULL, TRUE),
    ('URINE_SPECIFIC_GRAVITY', '요비중', '요비중', 'STANDARD', NULL, TRUE),
    ('URINE_SEDIMENT_RBC', '요침사 적혈구', '요침사적혈구', 'STANDARD', NULL, TRUE),
    ('URINE_SEDIMENT_WBC', '요침사 백혈구', '요침사백혈구', 'STANDARD', NULL, TRUE),
    ('URINE_SEDIMENT_CAST', '요침사 원주', '요침사원주', 'STANDARD', NULL, TRUE),
    ('URINE_SEDIMENT_OTHER', '요침사 기타', '요침사기타', 'STANDARD', NULL, TRUE),
    ('URINE_SEDIMENT_BACTERIA', '요침사 세균', '요침사세균', 'STANDARD', NULL, TRUE),
    ('URINE_SEDIMENT_EPITHELIAL_CELL', '요침사 상피세포', '요침사상피세포', 'STANDARD', NULL, TRUE),
    ('URINE_MICROALBUMIN_CREATININE_RATIO', '요미세알부민/크레아티닌 비율', '요미세알부민크레아티닌비율', 'STANDARD', NULL, TRUE),
    ('FECAL_OCCULT_BLOOD_QUANT', '분변잠혈 정량', '분변잠혈정량', 'STANDARD', NULL, TRUE),
    ('STOOL_PARASITE_SMEAR', '분변 기생충 도말검사', '분변기생충도말검사', 'STANDARD', NULL, TRUE),
    ('HEMATOCRIT', 'Hct', 'HCT', 'ABBREVIATION', NULL, TRUE),
    ('HEMATOCRIT', '헤마토크리트', '헤마토크리트', 'STANDARD', NULL, TRUE),
    ('HEMOGLOBIN', 'Hb', 'HB', 'ABBREVIATION', NULL, TRUE),
    ('HEMOGLOBIN', 'Hgb', 'HGB', 'ABBREVIATION', NULL, TRUE),
    ('HEMOGLOBIN', '혈색소', '혈색소', 'STANDARD', NULL, TRUE),
    ('WBC_COUNT', 'WBC', 'WBC', 'ABBREVIATION', NULL, TRUE),
    ('WBC_COUNT', '백혈구수', '백혈구수', 'STANDARD', NULL, TRUE),
    ('RBC_COUNT', 'RBC', 'RBC', 'ABBREVIATION', NULL, TRUE),
    ('RBC_COUNT', '적혈구수', '적혈구수', 'STANDARD', NULL, TRUE),
    ('PLATELET_COUNT', 'PLT', 'PLT', 'ABBREVIATION', NULL, TRUE),
    ('PLATELET_COUNT', '혈소판수', '혈소판수', 'STANDARD', NULL, TRUE),
    ('MCV', '평균적혈구용적', '평균적혈구용적', 'STANDARD', NULL, TRUE),
    ('MCH', '평균적혈구혈색소', '평균적혈구혈색소', 'STANDARD', NULL, TRUE),
    ('MCHC', '평균적혈구혈색소농도', '평균적혈구혈색소농도', 'STANDARD', NULL, TRUE),
    ('RDW', '적혈구분포계수', '적혈구분포계수', 'STANDARD', NULL, TRUE),
    ('PDW', '혈소판분포계수', '혈소판분포계수', 'STANDARD', NULL, TRUE),
    ('MPV', '평균혈소판용적', '평균혈소판용적', 'STANDARD', NULL, TRUE),
    ('PCT', '혈소판백분율', '혈소판백분율', 'STANDARD', NULL, TRUE),
    ('NEUTROPHIL_PERCENT', '호중구백분율', '호중구백분율', 'STANDARD', NULL, TRUE),
    ('EOSINOPHIL_PERCENT', '호산구백분율', '호산구백분율', 'STANDARD', NULL, TRUE),
    ('BASOPHIL_PERCENT', '호염구백분율', '호염구백분율', 'STANDARD', NULL, TRUE),
    ('MONOCYTE_PERCENT', '단핵구백분율', '단핵구백분율', 'STANDARD', NULL, TRUE),
    ('LYMPHOCYTE_PERCENT', '림프구백분율', '림프구백분율', 'STANDARD', NULL, TRUE),
    ('ESR', '적혈구침강속도', '적혈구침강속도', 'STANDARD', NULL, TRUE),
    ('AST', 'AST', 'AST', 'ABBREVIATION', NULL, TRUE),
    ('AST', 'GOT', 'GOT', 'ABBREVIATION', NULL, TRUE),
    ('AST', 'SGOT', 'SGOT', 'ABBREVIATION', NULL, TRUE),
    ('AST', '에이에스티(AST)', '에이에스티AST', 'STANDARD', NULL, TRUE),
    ('ALT', 'ALT', 'ALT', 'ABBREVIATION', NULL, TRUE),
    ('ALT', 'GPT', 'GPT', 'ABBREVIATION', NULL, TRUE),
    ('ALT', 'SGPT', 'SGPT', 'ABBREVIATION', NULL, TRUE),
    ('ALT', '에이엘티(ALT)', '에이엘티ALT', 'STANDARD', NULL, TRUE),
    ('GAMMA_GTP', 'γ-GTP', 'GAMMAGTP', 'SYNONYM', NULL, TRUE),
    ('GAMMA_GTP', 'GGT', 'GGT', 'ABBREVIATION', NULL, TRUE),
    ('GAMMA_GTP', 'GGTP', 'GGTP', 'ABBREVIATION', NULL, TRUE),
    ('GAMMA_GTP', 'r-GTP', 'RGTP', 'SYNONYM', NULL, TRUE),
    ('GAMMA_GTP', '감마지티피(γ-GTP)', '감마지티피GTP', 'STANDARD', NULL, TRUE),
    ('ALP', 'ALP', 'ALP', 'ABBREVIATION', NULL, TRUE),
    ('ALP', '알칼리인산분해효소(ALP)', '알칼리인산분해효소ALP', 'STANDARD', NULL, TRUE),
    ('TOTAL_BILIRUBIN', '총빌리루빈', '총빌리루빈', 'STANDARD', NULL, TRUE),
    ('DIRECT_BILIRUBIN', '직접빌리루빈', '직접빌리루빈', 'STANDARD', NULL, TRUE),
    ('INDIRECT_BILIRUBIN', '간접빌리루빈(계산값)', '간접빌리루빈계산값', 'STANDARD', NULL, TRUE),
    ('TOTAL_PROTEIN', '총단백', '총단백', 'STANDARD', NULL, TRUE),
    ('ALBUMIN', '알부민', '알부민', 'STANDARD', NULL, TRUE),
    ('AG_RATIO', '알부민/글로불린 비율', '알부민글로불린비율', 'STANDARD', NULL, TRUE),
    ('FIB4', 'FIB-4 간섬유화 지수', 'FIB4간섬유화지수', 'STANDARD', NULL, TRUE),
    ('FASTING_GLUCOSE', 'Fasting glucose', 'FASTINGGLUCOSE', 'SYNONYM', NULL, TRUE),
    ('FASTING_GLUCOSE', 'FBS', 'FBS', 'ABBREVIATION', NULL, TRUE),
    ('FASTING_GLUCOSE', '공복혈당', '공복혈당', 'STANDARD', NULL, TRUE),
    ('HBA1C', 'A1c', 'A1C', 'ABBREVIATION', NULL, TRUE),
    ('HBA1C', 'HbA1c', 'HBA1C', 'ABBREVIATION', NULL, TRUE),
    ('HBA1C', '당화혈색소(HbA1c)', '당화혈색소HBA1C', 'STANDARD', NULL, TRUE),
    ('TOTAL_CHOLESTEROL', 'T-Chol', 'TCHOL', 'ABBREVIATION', NULL, TRUE),
    ('TOTAL_CHOLESTEROL', 'Total cholesterol', 'TOTALCHOLESTEROL', 'SYNONYM', NULL, TRUE),
    ('TOTAL_CHOLESTEROL', '총콜레스테롤', '총콜레스테롤', 'STANDARD', NULL, TRUE),
    ('TRIGLYCERIDES', 'TG', 'TG', 'ABBREVIATION', NULL, TRUE),
    ('TRIGLYCERIDES', '중성지방', '중성지방', 'STANDARD', NULL, TRUE),
    ('HDL_CHOLESTEROL', 'HDL-C', 'HDLC', 'ABBREVIATION', NULL, TRUE),
    ('HDL_CHOLESTEROL', '고밀도(HDL) 콜레스테롤', '고밀도HDL콜레스테롤', 'STANDARD', NULL, TRUE),
    ('LDL_CHOLESTEROL', 'LDL-C', 'LDLC', 'ABBREVIATION', NULL, TRUE),
    ('LDL_CHOLESTEROL', '저밀도(LDL) 콜레스테롤', '저밀도LDL콜레스테롤', 'STANDARD', NULL, TRUE),
    ('BUN', 'BUN', 'BUN', 'ABBREVIATION', NULL, TRUE),
    ('BUN', '요소질소(BUN)', '요소질소BUN', 'STANDARD', NULL, TRUE),
    ('SERUM_CREATININE', 'Cr', 'CR', 'ABBREVIATION', NULL, TRUE),
    ('SERUM_CREATININE', 'Creatinine', 'CREATININE', 'SYNONYM', NULL, TRUE),
    ('SERUM_CREATININE', '혈청크레아티닌', '혈청크레아티닌', 'STANDARD', NULL, TRUE),
    ('BUN_CREATININE_RATIO', '요소질소/크레아티닌 비율', '요소질소크레아티닌비율', 'STANDARD', NULL, TRUE),
    ('EGFR', 'eGFR', 'EGFR', 'ABBREVIATION', NULL, TRUE),
    ('EGFR', '신사구체여과율(e-GFR)', '신사구체여과율EGFR', 'STANDARD', NULL, TRUE),
    ('URIC_ACID', 'Uric acid', 'URICACID', 'SYNONYM', NULL, TRUE),
    ('URIC_ACID', '요산', '요산', 'STANDARD', NULL, TRUE),
    ('HS_CRP', 'hs-CRP', 'HSCRP', 'ABBREVIATION', NULL, TRUE),
    ('HS_CRP', '고감도 C반응단백(hs-CRP)', '고감도C반응단백HSCRP', 'STANDARD', NULL, TRUE),
    ('HEPATITIS_B_SURFACE_ANTIGEN', 'B형간염 표면항원(HBsAg)', 'B형간염표면항원HBSAG', 'STANDARD', NULL, TRUE),
    ('HEPATITIS_B_SURFACE_ANTIGEN', 'HBsAg', 'HBSAG', 'ABBREVIATION', NULL, TRUE),
    ('HEPATITIS_B_SURFACE_ANTIBODY', 'B형간염 표면항체(HBsAb)', 'B형간염표면항체HBSAB', 'STANDARD', NULL, TRUE),
    ('HEPATITIS_B_SURFACE_ANTIBODY', 'HBsAb', 'HBSAB', 'ABBREVIATION', NULL, TRUE),
    ('HEPATITIS_C_ANTIBODY', 'C형간염 항체(HCV Ab)', 'C형간염항체HCVAB', 'STANDARD', NULL, TRUE),
    ('HEPATITIS_C_ANTIBODY', 'HCV Ab', 'HCVAB', 'ABBREVIATION', NULL, TRUE),
    ('PSA', 'PSA', 'PSA', 'ABBREVIATION', NULL, TRUE),
    ('PSA', '전립선특이항원(PSA)', '전립선특이항원PSA', 'STANDARD', NULL, TRUE),
    ('AFP', 'AFP', 'AFP', 'ABBREVIATION', NULL, TRUE),
    ('AFP', '알파태아단백(AFP)', '알파태아단백AFP', 'STANDARD', NULL, TRUE),
    ('CA19_9', 'CA 19-9', 'CA199', 'ABBREVIATION', NULL, TRUE),
    ('TSH', 'TSH', 'TSH', 'ABBREVIATION', NULL, TRUE),
    ('TSH', '갑상선자극호르몬(TSH)', '갑상선자극호르몬TSH', 'STANDARD', NULL, TRUE),
    ('FREE_T4', 'Free T4', 'FREET4', 'ABBREVIATION', NULL, TRUE),
    ('FREE_T4', 'FT4', 'FT4', 'ABBREVIATION', NULL, TRUE),
    ('FREE_T4', '유리티록신(Free T4)', '유리티록신FREET4', 'STANDARD', NULL, TRUE),
    ('T3', 'T3', 'T3', 'ABBREVIATION', NULL, TRUE),
    ('T3', '트리요오드티로닌(T3)', '트리요오드티로닌T3', 'STANDARD', NULL, TRUE),
    ('BONE_DENSITY', '골밀도검사', '골밀도검사', 'STANDARD', NULL, TRUE),
    ('PULMONARY_FUNCTION', '폐기능검사', '폐기능검사', 'STANDARD', NULL, TRUE),
    ('PHQ9', '정신건강검사(우울증, PHQ-9)', '정신건강검사우울증PHQ9', 'STANDARD', NULL, TRUE),
    ('CAPE15', '정신건강검사(조기정신증, CAPE-15)', '정신건강검사조기정신증CAPE15', 'STANDARD', NULL, TRUE),
    ('KDSQC', '인지기능장애검사(KDSQ-C)', '인지기능장애검사KDSQC', 'STANDARD', NULL, TRUE),
    ('LIFESTYLE_ASSESSMENT', '생활습관평가', '생활습관평가', 'STANDARD', NULL, TRUE),
    ('ELDERLY_PHYSICAL_FUNCTION', '노인신체기능검사', '노인신체기능검사', 'STANDARD', NULL, TRUE),
    ('DENTAL_PLAQUE', '치면세균막검사', '치면세균막검사', 'STANDARD', NULL, TRUE),
    ('CERVICAL_CYTOLOGY', '자궁경부 세포검사', '자궁경부세포검사', 'STANDARD', NULL, TRUE),
    ('UPPER_GI_SERIES', '위장조영촬영', '위장조영촬영', 'STANDARD', NULL, TRUE),
    ('UPPER_GI_ENDOSCOPY', 'EGD', 'EGD', 'ABBREVIATION', NULL, TRUE),
    ('UPPER_GI_ENDOSCOPY', '위내시경', '위내시경', 'SYNONYM', NULL, TRUE),
    ('UPPER_GI_ENDOSCOPY', '일반 위내시경', '일반위내시경', 'STANDARD', NULL, TRUE),
    ('MAMMOGRAPHY', 'Mammography', 'MAMMOGRAPHY', 'SYNONYM', NULL, TRUE),
    ('MAMMOGRAPHY', '유방 X선', '유방X선', 'SYNONYM', NULL, TRUE),
    ('MAMMOGRAPHY', '유방촬영', '유방촬영', 'STANDARD', NULL, TRUE),
    ('THYROID_ULTRASOUND', '갑상선초음파', '갑상선초음파', 'STANDARD', NULL, TRUE),
    ('UPPER_ABDOMINAL_ULTRASOUND', 'Abdominal US', 'ABDOMINALUS', 'ABBREVIATION', NULL, TRUE),
    ('UPPER_ABDOMINAL_ULTRASOUND', '복부초음파', '복부초음파', 'SYNONYM', NULL, TRUE),
    ('UPPER_ABDOMINAL_ULTRASOUND', '상복부초음파', '상복부초음파', 'STANDARD', NULL, TRUE),
    ('GLOBULIN', '글로불린', '글로불린', 'STANDARD', NULL, TRUE),
    ('LDH', 'LDH', 'LDH', 'ABBREVIATION', NULL, TRUE),
    ('LDH', '젖산탈수소효소(LDH)', '젖산탈수소효소LDH', 'STANDARD', NULL, TRUE),
    ('SODIUM', 'Na', 'NA', 'ABBREVIATION', NULL, TRUE),
    ('SODIUM', '나트륨', '나트륨', 'STANDARD', NULL, TRUE),
    ('POTASSIUM', 'K', 'K', 'ABBREVIATION', NULL, TRUE),
    ('POTASSIUM', '칼륨', '칼륨', 'STANDARD', NULL, TRUE),
    ('CHLORIDE', 'Cl', 'CL', 'ABBREVIATION', NULL, TRUE),
    ('CHLORIDE', '염소', '염소', 'STANDARD', NULL, TRUE),
    ('CALCIUM', 'Ca', 'CA', 'ABBREVIATION', NULL, TRUE),
    ('CALCIUM', '칼슘', '칼슘', 'STANDARD', NULL, TRUE),
    ('PHOSPHORUS', 'P', 'P', 'ABBREVIATION', NULL, TRUE),
    ('PHOSPHORUS', '인', '인', 'STANDARD', NULL, TRUE),
    ('MAGNESIUM', 'Mg', 'MG', 'ABBREVIATION', NULL, TRUE),
    ('MAGNESIUM', '마그네슘', '마그네슘', 'STANDARD', NULL, TRUE),
    ('AMYLASE', 'Amylase', 'AMYLASE', 'SYNONYM', NULL, TRUE),
    ('AMYLASE', '아밀라아제', '아밀라아제', 'STANDARD', NULL, TRUE),
    ('LIPASE', 'Lipase', 'LIPASE', 'SYNONYM', NULL, TRUE),
    ('LIPASE', '리파아제', '리파아제', 'STANDARD', NULL, TRUE),
    ('IRON', 'Fe', 'FE', 'ABBREVIATION', NULL, TRUE),
    ('IRON', '혈청철', '혈청철', 'STANDARD', NULL, TRUE),
    ('TIBC', 'TIBC', 'TIBC', 'ABBREVIATION', NULL, TRUE),
    ('TIBC', '총철결합능(TIBC)', '총철결합능TIBC', 'STANDARD', NULL, TRUE),
    ('UIBC', 'UIBC', 'UIBC', 'ABBREVIATION', NULL, TRUE),
    ('UIBC', '불포화철결합능(UIBC)', '불포화철결합능UIBC', 'STANDARD', NULL, TRUE),
    ('FERRITIN', 'Ferritin', 'FERRITIN', 'SYNONYM', NULL, TRUE),
    ('FERRITIN', '페리틴', '페리틴', 'STANDARD', NULL, TRUE),
    ('VITAMIN_D_25_OH', '25-OH Vitamin D', '25OHVITAMIND', 'SYNONYM', NULL, TRUE),
    ('VITAMIN_D_25_OH', '25-OH 비타민D', '25OH비타민D', 'STANDARD', NULL, TRUE),
    ('CEA', 'CEA', 'CEA', 'ABBREVIATION', NULL, TRUE),
    ('CEA', '암배아항원(CEA)', '암배아항원CEA', 'STANDARD', NULL, TRUE),
    ('CA125', 'CA 125', 'CA125', 'ABBREVIATION', NULL, TRUE),
    ('CYFRA21_1', 'CYFRA 21-1', 'CYFRA211', 'ABBREVIATION', NULL, TRUE),
    ('HE4', 'HE4', 'HE4', 'ABBREVIATION', NULL, TRUE),
    ('ROMA_SCORE', 'ROMA 점수', 'ROMA점수', 'STANDARD', NULL, TRUE),
    ('HIV_AG_AB', 'HIV Ag/Ab', 'HIVAGAB', 'ABBREVIATION', NULL, TRUE),
    ('HIV_AG_AB', 'HIV 항원·항체', 'HIV항원항체', 'STANDARD', NULL, TRUE),
    ('SYPHILIS_SCREEN', 'RPR', 'RPR', 'ABBREVIATION', NULL, TRUE),
    ('SYPHILIS_SCREEN', 'VDRL', 'VDRL', 'ABBREVIATION', NULL, TRUE),
    ('SYPHILIS_SCREEN', '매독 선별검사', '매독선별검사', 'STANDARD', NULL, TRUE),
    ('HEPATITIS_A_ANTIBODY', 'A형간염 항체', 'A형간염항체', 'STANDARD', NULL, TRUE),
    ('RHEUMATOID_FACTOR', 'RF', 'RF', 'ABBREVIATION', NULL, TRUE),
    ('RHEUMATOID_FACTOR', '류마티스인자(RF)', '류마티스인자RF', 'STANDARD', NULL, TRUE),
    ('CK', 'CPK', 'CPK', 'ABBREVIATION', NULL, TRUE),
    ('CK', '크레아틴키나아제(CK)', '크레아틴키나아제CK', 'STANDARD', NULL, TRUE),
    ('CYSTATIN_C', 'Cystatin C', 'CYSTATINC', 'SYNONYM', NULL, TRUE),
    ('CYSTATIN_C', '시스타틴 C', '시스타틴C', 'STANDARD', NULL, TRUE),
    ('TESTOSTERONE', '테스토스테론', '테스토스테론', 'STANDARD', NULL, TRUE),
    ('FSH', '난포자극호르몬(FSH)', '난포자극호르몬FSH', 'STANDARD', NULL, TRUE),
    ('ESTRADIOL', '에스트라디올(E2)', '에스트라디올E2', 'STANDARD', NULL, TRUE),
    ('ABO_BLOOD_GROUP', 'ABO type', 'ABOTYPE', 'SYNONYM', NULL, TRUE),
    ('ABO_BLOOD_GROUP', 'ABO 혈액형', 'ABO혈액형', 'STANDARD', NULL, TRUE),
    ('RH_BLOOD_GROUP', 'Rh type', 'RHTYPE', 'SYNONYM', NULL, TRUE),
    ('RH_BLOOD_GROUP', 'Rh 혈액형', 'RH혈액형', 'STANDARD', NULL, TRUE),
    ('PULSE', 'Heart rate', 'HEARTRATE', 'SYNONYM', NULL, TRUE),
    ('PULSE', 'HR', 'HR', 'ABBREVIATION', NULL, TRUE),
    ('PULSE', '맥박', '맥박', 'STANDARD', NULL, TRUE),
    ('OXYGEN_SATURATION', 'SpO2', 'SPO2', 'ABBREVIATION', NULL, TRUE),
    ('OXYGEN_SATURATION', '산소포화도', '산소포화도', 'STANDARD', NULL, TRUE),
    ('FEV1', '1초간 노력성 호기량(FEV1)', '1초간노력성호기량FEV1', 'STANDARD', NULL, TRUE),
    ('FEV1', 'FEV1', 'FEV1', 'ABBREVIATION', NULL, TRUE),
    ('FVC', 'FVC', 'FVC', 'ABBREVIATION', NULL, TRUE),
    ('FVC', '노력성 폐활량(FVC)', '노력성폐활량FVC', 'STANDARD', NULL, TRUE),
    ('FEV1_FVC_RATIO', 'FEV1/FVC', 'FEV1FVC', 'ABBREVIATION', NULL, TRUE),
    ('FEV1_FVC_RATIO', 'FEV1/FVC 비율', 'FEV1FVC비율', 'STANDARD', NULL, TRUE),
    ('BONE_DENSITY_T_SCORE', 'T-score', 'TSCORE', 'ABBREVIATION', NULL, TRUE),
    ('BONE_DENSITY_T_SCORE', '골밀도 T-score', '골밀도TSCORE', 'STANDARD', NULL, TRUE),
    ('BONE_DENSITY_Z_SCORE', 'Z-score', 'ZSCORE', 'ABBREVIATION', NULL, TRUE),
    ('BONE_DENSITY_Z_SCORE', '골밀도 Z-score', '골밀도ZSCORE', 'STANDARD', NULL, TRUE),
    ('ABDOMINAL_CT', '복부 CT', '복부CT', 'STANDARD', NULL, TRUE),
    ('LOW_DOSE_CHEST_CT', 'LDCT', 'LDCT', 'ABBREVIATION', NULL, TRUE),
    ('LOW_DOSE_CHEST_CT', '저선량 흉부 CT', '저선량흉부CT', 'STANDARD', NULL, TRUE),
    ('CORONARY_CALCIUM_CT', '관상동맥 석회화 CT', '관상동맥석회화CT', 'STANDARD', NULL, TRUE),
    ('BRAIN_MRI', 'Brain MRI', 'BRAINMRI', 'SYNONYM', NULL, TRUE),
    ('BRAIN_MRI', '뇌 MRI', '뇌MRI', 'STANDARD', NULL, TRUE),
    ('BRAIN_MRA', 'Brain MRA', 'BRAINMRA', 'SYNONYM', NULL, TRUE),
    ('BRAIN_MRA', '뇌 MRA', '뇌MRA', 'STANDARD', NULL, TRUE),
    ('CAROTID_ULTRASOUND', 'Carotid US', 'CAROTIDUS', 'ABBREVIATION', NULL, TRUE),
    ('CAROTID_ULTRASOUND', '경동맥초음파', '경동맥초음파', 'STANDARD', NULL, TRUE),
    ('ECHOCARDIOGRAPHY', 'Echo', 'ECHO', 'ABBREVIATION', NULL, TRUE),
    ('ECHOCARDIOGRAPHY', '심장초음파', '심장초음파', 'STANDARD', NULL, TRUE),
    ('BREAST_ULTRASOUND', '유방초음파', '유방초음파', 'STANDARD', NULL, TRUE),
    ('PELVIC_ULTRASOUND', '부인과초음파', '부인과초음파', 'STANDARD', NULL, TRUE),
    ('PROSTATE_ULTRASOUND', '전립선초음파', '전립선초음파', 'STANDARD', NULL, TRUE),
    ('COLONOSCOPY', '대장내시경', '대장내시경', 'SYNONYM', NULL, TRUE),
    ('LIVER_FIBROSIS_SCAN', '간 섬유화·지방 스캔', '간섬유화지방스캔', 'STANDARD', NULL, TRUE),
    ('HPV_TEST', 'HPV', 'HPV', 'ABBREVIATION', NULL, TRUE),
    ('HPV_TEST', '인유두종바이러스(HPV) 검사', '인유두종바이러스HPV검사', 'STANDARD', NULL, TRUE),
    ('CBC_PANEL', 'CBC', 'CBC', 'ABBREVIATION', NULL, TRUE),
    ('CBC_PANEL', '일반혈액검사 패널(CBC)', '일반혈액검사패널CBC', 'STANDARD', NULL, TRUE),
    ('LIVER_FUNCTION_PANEL', 'LFT', 'LFT', 'ABBREVIATION', NULL, TRUE),
    ('LIVER_FUNCTION_PANEL', '간기능검사 패널', '간기능검사패널', 'STANDARD', NULL, TRUE),
    ('LIPID_PANEL', 'Lipid profile', 'LIPIDPROFILE', 'SYNONYM', NULL, TRUE),
    ('LIPID_PANEL', '지질검사 패널', '지질검사패널', 'STANDARD', NULL, TRUE),
    ('THYROID_FUNCTION_PANEL', 'TFT', 'TFT', 'ABBREVIATION', NULL, TRUE),
    ('THYROID_FUNCTION_PANEL', '갑상선기능검사 패널', '갑상선기능검사패널', 'STANDARD', NULL, TRUE),
    ('URINALYSIS_PANEL', 'UA', 'UA', 'ABBREVIATION', NULL, TRUE),
    ('URINALYSIS_PANEL', 'Urinalysis', 'URINALYSIS', 'SYNONYM', NULL, TRUE),
    ('URINALYSIS_PANEL', '요검사 패널', '요검사패널', 'STANDARD', NULL, TRUE)
)
INSERT INTO labs_item_alias (
    item_id, alias_name, normalized_alias, alias_type, institution_name, is_active
)
SELECT
    item.item_id,
    alias_data.alias_name,
    alias_data.normalized_alias,
    alias_data.alias_type,
    alias_data.institution_name,
    alias_data.is_active
FROM alias_data
JOIN labs_item_master AS item
    ON item.item_code = alias_data.item_code
ON CONFLICT (normalized_alias, institution_name)
DO UPDATE SET
    item_id = EXCLUDED.item_id,
    alias_name = EXCLUDED.alias_name,
    alias_type = EXCLUDED.alias_type,
    is_active = EXCLUDED.is_active;

COMMIT;
